services:
  - type: web
    name: monthly-wrapped
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: node server/app.js
    envVars:
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: CLIENT_URL
        sync: false
